In [1]:
!pip install faiss-cpu requests

In [1]:
import faiss
import requests
import numpy as np

### <font color="green">Delete index to clear all the records</font>

In [ ]:
# del index

In [4]:
dataset = [
    "AGEYE is an industry-leading provider of turnkey vertical farming solutions, combining space-efficient automated racking systems with advanced AI-powered farm management and crop intelligence software.",
    "Our technology empowers vertical farm operators to enhance their entire farming operation, efficiently manage resources, and significantly increase crop yield with minimal environmental impact.",
    "A fully automated and scalable vertical farming system, integrating cutting-edge robotics, fertigation, and robust racking.",
    "By integrating advanced analytics and automation, we enable smarter decision-making, reduce waste, and ensure sustainable growth.",
    "Digital Cultivation Farm, A farm management and resource planning platform that centralizes all the data collected into an easy to use dashboard that presents a holistic view of the growing operation.",
    "Management Software, A farm management and resource planning platform that centralizes all the data collected into an easy to use dashboard that presents a holistic view of the growing operation.",
    "arrow_right, Harnessing AI, we analyze real-time data on environmental conditions and plant health, while automation optimizes all farming stages, from irrigation to harvest, for peak efficiency and less labor.",
    "Want to see it in action?Request a Demo",
    "AGEYE is committed to making indoor farming both sustainable and profitable. Our goal is clear: to ensure fresh, nutritious, and sustainable food is accessible to all. Using cutting-edge technology, we provide a holistic solution that leads the market in indoor food production. Our efficient system enables indoor farmers to produce more crops at higher yields and reduced costs, enhancing local food availability.",
    "Indoor Crops icon, To grow the most nutritious and fresh crops while significantly elevating the quality of each harvest.",
    "It is a full Automation?"
    "Efficient and practical robotics technology significantly reduces human errors, improves plant health, and lowers labor costs, all without the substantial financial investment typically required by advanced technologies. Robotic seeding, planting, scouting, harvesting, tray washing, and more accelerates the farming process to ensure efficient crop turns and yields."
]

In [11]:
len(dataset)

11

In [2]:

import requests
import numpy as np

def generate_embeddings(text):
    url = "https://api.euron.one/api/v1/euri/embeddings"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer euri-698e554ded59d10cc4bec9b2c00332697486fe48efa31bb0745b24c5865ce945"
    }
    payload = {
        "input": text,
        "model": "text-embedding-3-small"
    }

    response = requests.post(url, headers=headers, json=payload)
    data = response.json()
    
    embedding = np.array(data['data'][0]['embedding'])
    
    return embedding

In [5]:
embeddings = []
for idx, i in enumerate(dataset):
    emb = generate_embeddings(i)
    embeddings.append(emb) 

In [6]:
embeddings

[array([-0.01085984, -0.00018788,  0.04598059, ...,  0.00469865,
        -0.01532686,  0.00960245], shape=(1536,)),
 array([-0.00577769,  0.01821927,  0.04191699, ...,  0.01607854,
        -0.01530741,  0.0109799 ], shape=(1536,)),
 array([-0.02621849, -0.0025905 ,  0.02385262, ...,  0.03027796,
        -0.0116936 , -0.01191338], shape=(1536,)),
 array([ 0.01272636,  0.03824762,  0.06013605, ..., -0.00765409,
         0.02481297,  0.00518651], shape=(1536,)),
 array([ 0.01697121,  0.02649036,  0.0335211 , ..., -0.00993388,
        -0.00135694,  0.00686616], shape=(1536,)),
 array([-0.00385388,  0.05190577,  0.02866833, ...,  0.0027635 ,
         0.01522329, -0.00066534], shape=(1536,)),
 array([ 0.00658114,  0.04148352,  0.05326346, ..., -0.01873837,
        -0.00653105,  0.00635742], shape=(1536,)),
 array([-0.05717145, -0.00150399, -0.070083  , ..., -0.01212639,
        -0.01070874, -0.02431095], shape=(1536,)),
 array([ 0.00219867,  0.01470432,  0.04304934, ...,  0.02434322,
       

In [8]:
len(embeddings[0])

1536

In [9]:
embeddings_array = np.vstack(embeddings)

In [10]:
embeddings_array

array([[-0.01085984, -0.00018788,  0.04598059, ...,  0.00469865,
        -0.01532686,  0.00960245],
       [-0.00577769,  0.01821927,  0.04191699, ...,  0.01607854,
        -0.01530741,  0.0109799 ],
       [-0.02621849, -0.0025905 ,  0.02385262, ...,  0.03027796,
        -0.0116936 , -0.01191338],
       ...,
       [ 0.00219867,  0.01470432,  0.04304934, ...,  0.02434322,
        -0.02994043, -0.00445384],
       [ 0.00697922,  0.03235706,  0.01389465, ..., -0.01252943,
        -0.025952  , -0.01527264],
       [-0.00768704,  0.00544638,  0.01584158, ...,  0.00979747,
        -0.01395822,  0.03061459]], shape=(11, 1536))

In [17]:
embeddings_array.shape

(11, 1536)

In [15]:
dimension = embeddings_array.shape[1]

In [16]:
dimension

1536

In [ ]:
dimension = embeddings_array.shape[1]
index = faiss.IndexFlatL2(dimension) # L2 -> eulidean

In [19]:
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x00000254745F45D0> >

In [20]:
index.add(embeddings_array)

In [ ]:
index.ntotal # To check total no.of count in the dataset

11

### <font color="green">Adding a single prompt into VectorDB (FAISS) </font>

In [22]:
text = """Grow More./
          Worry Less. /
          Digital Cultivation’s flexibility allows indoor growers with unique farm configurations to personalize the platform to suit their individual requirements, 
          enhancing efficiency and increasing productivity throughout their operations."""

In [23]:
new_data = generate_embeddings(text).reshape(1,-1)

In [24]:
index.add(new_data)

In [ ]:
index.ntotal # to store in the in-memory of RAM

12

In [ ]:
faiss.write_index(index, "ageye-metadata-vectordb.faiss") # presistance to dump with faiss index

In [27]:
query = "Tell me about AGEYE?"

In [28]:
query_vec = generate_embeddings(query).reshape(1,-1)

In [29]:
query_vec

array([[-0.00894673, -0.01276773, -0.02675415, ...,  0.01022278,
        -0.0159722 ,  0.00478521]], shape=(1, 1536))

#### <font color="green">Top K=2 Similarity of data</font>

So, based on the distances you can try to check it. So less meaning is that most similar distance is little bit higher. Similar that the second one, lesser then similar third one in this way you can try to select like a top most similarity context.

In [31]:
distance, indices = index.search(query_vec, k=2)

In [32]:
distance

array([[1.1709771, 1.3203232]], dtype=float32)

In [33]:
indices

array([[0, 8]])

In [34]:
dataset[0]

'AGEYE is an industry-leading provider of turnkey vertical farming solutions, combining space-efficient automated racking systems with advanced AI-powered farm management and crop intelligence software.'

In [35]:
dataset[8]

'AGEYE is committed to making indoor farming both sustainable and profitable. Our goal is clear: to ensure fresh, nutritious, and sustainable food is accessible to all. Using cutting-edge technology, we provide a holistic solution that leads the market in indoor food production. Our efficient system enables indoor farmers to produce more crops at higher yields and reduced costs, enhancing local food availability.'

#### <font color="green">Top K=5 Similarity of data</font>

In [ ]:
distance, indices = index.search(query_vec, k=5)

In [37]:
distance

array([[1.1709771, 1.3203232, 1.5045319, 1.522274 , 1.5251253]],
      dtype=float32)

In [38]:
indices

array([[ 0,  8, 11,  7,  6]])

In [39]:
dataset[0]

'AGEYE is an industry-leading provider of turnkey vertical farming solutions, combining space-efficient automated racking systems with advanced AI-powered farm management and crop intelligence software.'

In [40]:
dataset[8]

'AGEYE is committed to making indoor farming both sustainable and profitable. Our goal is clear: to ensure fresh, nutritious, and sustainable food is accessible to all. Using cutting-edge technology, we provide a holistic solution that leads the market in indoor food production. Our efficient system enables indoor farmers to produce more crops at higher yields and reduced costs, enhancing local food availability.'

In [42]:
dataset[7]

'Want to see it in action?Request a Demo'

In [43]:
dataset[6]

'arrow_right, Harnessing AI, we analyze real-time data on environmental conditions and plant health, while automation optimizes all farming stages, from irrigation to harvest, for peak efficiency and less labor.'